### ISSUE TITLE
Lockmaster should pass each river parser the timestamp of the last stored data point

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/river-view#48]
This will help parsers be more efficient, so they do not submit data that has already been submitted.

Depends on #53.

**Comment by rhyolight** [comment]
CC @passiweinberger

**Comment by rhyolight** [comment]
Might want to change the parser params from

```
function(config, body, url, temporalDataCallback, metaDataCallback) {
};
```

to

```
function(body, options, temporalDataCallback, metaDataCallback) {
    options.config;
    options.url;
    options.lastTimestamp;
};
```

**Comment by passiweinberger** [comment]
:+1:

**Comment by rhyolight** [comment]
I'm having second thoughts about this. @jaredweiss I would like your opinion. 

First of all, the whole reason I wanted to pass a timestamp to the parser was so the parser could make an intelligent decision about whether a data point has already been saved or not, thus increasing the efficiency of River View if the parser used this info. But...

1. The parser may ignore it.
1. The performance cost of getting all the necessary timestamps may be too high for some rivers
1. If the parser is written properly and polls at the correct interval, it may be more efficient for it to just overwrite existing data than for RV to retrieve all the timestamps.

If this were as simple as providing one timestamp to the parser, I would totally do it, but the lockmaster needs to get all the stream ids first, then query each redis sorted set for each stream id for the last updated time (this could be hundreds of redis calls), then provide an associative array of streamed==>timestamp values to the parser. At that point, the parser may ignore the timestamps entirely, making all that effort for naught.

**Comment by jaredweiss** [comment]
@rhyolight
Just spent a bit of time thinking this problem out. I think you're right in bringing up the question of where to get the most recent timestamp from. It seems that with the way river-view is currently set up, we'd need to be making a redis call for each of these last timestamps and that could easily occupy the same resources we'd be trying to offload. 

It seems like the way something like this would be most beneficial is if we were sending large queries to Redis every time we wrote a new record. If the queries we'd be sending to request the timestamp are roughly the same size as the ones we'd be sending to write new rows, I don't think we'd be saving much effort. 

A possible alternative to future-proof this project might be to set up a set in redis specifically for associating timestamps with rivers, and whenever new data is pushed to a river, the timestamp associated with the river's key would be overwritten. This could be useful if the parsers get more complicated or the rivers start writing a lot more data, but otherwise it might make more sense to just leave the current implementation as is.

**Comment by rhyolight** [comment]
> A possible alternative to future-proof this project might be to set up a set in redis specifically for associating timestamps with rivers, and whenever new data is pushed to a river, the timestamp associated with the river's key would be overwritten.

Something like this could work well. I'll think some more about it.

**Comment by rhyolight** [comment]
Whatever the answer it, it's not captured in this issue.
